# Training configuration for PPO navigation agent

# PPO hyperparameters
ppo:
  num_train_steps: 2048
  batch_size: 64
  n_epochs: 10
  learning_rate: 3.0e-4
  gamma: 0.98
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  verbose: 1

# A2C hyperparameters
a2c:
  n_steps: 5
  learning_rate: 3.0e-4
  gamma: 0.99
  gae_lambda: 0.95
  ent_coef: 0.01
  vf_coef: 0.5
  verbose: 1

agent:
  memory: null #choose from null, 'stacking', 'lstm'
  horizon: 10 #used only in the stacking case

  backbone:
    cnn_filters:
      - [16, 3, 1]
      - [32, 3, 1]
      - [32, 3, 1]
    cnn_activation: "relu"
    num_res_blocks: 3
    feature_size: 64

  icm:
    cnn_filters:
      - [16, 3, 1]
      - [32, 3, 1]
      - [32, 3, 1]
    cnn_activation: "relu"
    num_res_blocks: 3
    feature_size: 64

  policy:
    net_arch:
      pi: [64, 64]
      vf: [64, 64]

# Training settings
training:
  total_timesteps: 200000
  save_path: ppo_nav_agent

# Logging settings
logging:
  reward_avg_every_n_rollouts: 400
  log_gifs: true
  gif_rollout_steps: 40
  log_gif_every_n_rollouts: 1000
