# Training configuration for PPO navigation agent

# PPO hyperparameters
ppo:
  num_train_steps: 2048
  batch_size: 64
  n_epochs: 1 # only train once over data to keep icm learning on-policy
  learning_rate: 3.0e-4
  gamma: 0.98
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  verbose: 1

  train_icm: true
  normalize_rewards: false #NOTE not being passed  #if true we normalise by the mean intrinsic reward of the last rollout
  eta: 1.0 #loss to reward factor
  beta: 0.005 #forwards loss weighting
  lambda: 1.0 #original loss factor

agent:
  memory: null #choose from null, 'stacking', 'lstm'
  horizon: 10 #used only in the stacking case

  backbone:
    cnn_filters:
      - [16, 3, 1]
      - [32, 3, 1]
      - [32, 3, 1]
    cnn_activation: "relu"
    num_res_blocks: 3
    feature_size: 64

  icm:
    cnn_filters:
      - [16, 3, 1]
      - [32, 3, 1]
      - [32, 3, 1]
    cnn_activation: "relu"
    num_res_blocks: 3
    feature_size: 64

  policy:
    net_arch:
      pi: [64, 64]
      vf: [64, 64]

# Training settings
training:
  total_timesteps: 500000
  save_path: ppo_nav_agent

# Logging settings
logging:
  log_gifs: false
  gif_rollout_steps: 30
  log_gif_every_n_rollouts: 5
